name: Deploy to Windows Server

on:
  push:
    branches:
      - main  # Adjust if your production branch is different

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu to perform the build steps

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    ## ---- Build Backend (Node.js) ---- ##
    - name: Setup Node.js for Backend
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install

    - name: Build Backend
      run: |
        cd backend
        npm run build

    ## ---- Build Frontend (Angular) ---- ##
    - name: Setup Node.js for Frontend
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Angular CLI globally
      run: npm install -g @angular/cli

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install

    - name: Build Angular App
      run: |
        cd frontend
        ng build --configuration=production

    ## ---- Deploy to Windows Server ---- ##
    - name: Copy Files to Windows Server via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.WINDOWS_SERVER_IP }}
        username: ${{ secrets.WINDOWS_SERVER_USER }}
        password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
        source: "backend/, frontend/dist/"
        target: "C:/deploy/app"

    - name: Restart Services on Windows Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.WINDOWS_SERVER_IP }}
        username: ${{ secrets.WINDOWS_SERVER_USER }}
        password: ${{ secrets.WINDOWS_SERVER_PASSWORD }}
        script: |
          cd C:/deploy/app/backend
          pm2 restart all || pm2 start index.js --name my-app
          iisreset
